version: '3.8'

services:
  php:
    image: yiisoftware/yii2-php:8.2-apache
    container_name: yii2-app
    volumes:
      - ./:/app:delegated
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    ports:
      - '8000:80'
    environment:
      - DB_HOST=mysql
      - DB_NAME=yii2db
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - mysql
    command: >
      /bin/sh -c "
      composer install &&
      php yii migrate --interactive=0 &&
      apache2-foreground
      "

  mysql:
    image: mysql:8.1
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root

volumes:
  mysql-data:
